10/11/2024 04:24:06 - INFO - llamafactory.cli - Initializing distributed tasks at: 127.0.0.1:20444
W1011 04:24:07.577000 23204694173504 torch/distributed/run.py:757] 
W1011 04:24:07.577000 23204694173504 torch/distributed/run.py:757] *****************************************
W1011 04:24:07.577000 23204694173504 torch/distributed/run.py:757] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W1011 04:24:07.577000 23204694173504 torch/distributed/run.py:757] *****************************************
Traceback (most recent call last):
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/LLaMA-Factory/src/llamafactory/launcher.py", line 15, in <module>
  File "/iitjhome/m23csa016/meesho_code/LLaMA-Factory/src/llamafactory/launcher.py", line 15, in <module>
        from llamafactory.train.tuner import run_exp  # use absolute importfrom llamafactory.train.tuner import run_exp  # use absolute import

ModuleNotFoundErrorModuleNotFoundError: : No module named 'llamafactory'No module named 'llamafactory'

E1011 04:24:12.604000 23204694173504 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 167952) of binary: /scratch/apps/packages/python/3.10/bin/python3.10
Traceback (most recent call last):
  File "/scratch/apps/packages/python/3.10/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/scratch/apps/packages/python/3.10/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/scratch/apps/packages/python/3.10/lib/python3.10/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/scratch/apps/packages/python/3.10/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/scratch/apps/packages/python/3.10/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/scratch/apps/packages/python/3.10/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/iitjhome/m23csa016/meesho_code/LLaMA-Factory/src/llamafactory/launcher.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-10-11_04:24:12
  host      : cn26.iitj.ac.in
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 167953)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-11_04:24:12
  host      : cn26.iitj.ac.in
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 167952)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
